apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
    - name: tools
      image: nicolaka/netshoot:latest
      command: ["sleep", "7200"]
      resources:
        requests: {cpu: 10m, memory: 16Mi}
